// Centralized projects data and helpers

export const projects = [
  {
    id: 1,
    slug: "anil-shah-residence",
    title: "Anil Shah Residence",
    category: "Residential Design",
    mainImage: "/projects/ANIL SHAH/1 (1).jpg",
    thumbnail: "/projects/ANIL SHAH/1 (1).jpg",
    images: [
      "/projects/ANIL SHAH/1 (1).jpg",
      "/projects/ANIL SHAH/1 (2).jpg",
      "/projects/ANIL SHAH/1 (4).jpg",
      "/projects/ANIL SHAH/1 (5).jpg",
      "/projects/ANIL SHAH/1 (6).jpg",
      "/projects/ANIL SHAH/2 (1).jpg",
      "/projects/ANIL SHAH/2 (2).jpg",
      "/projects/ANIL SHAH/2 (3).jpg",
      "/projects/ANIL SHAH/2 (4).jpg",
      "/projects/ANIL SHAH/2 (6).jpg",
      "/projects/ANIL SHAH/2 (7).jpg",
      "/projects/ANIL SHAH/2 (8).jpg",
      "/projects/ANIL SHAH/4 (1).jpg",
      "/projects/ANIL SHAH/4 (2).jpg",
      "/projects/ANIL SHAH/4 (3).jpg",
      "/projects/ANIL SHAH/5 (1).jpg",
      "/projects/ANIL SHAH/5 (2).jpg",
      "/projects/ANIL SHAH/6 (3).jpg",
      "/projects/ANIL SHAH/6 (4).jpg",
      "/projects/ANIL SHAH/6 (5).jpg",
      "/projects/ANIL SHAH/6 (6).jpg",
      "/projects/ANIL SHAH/6 (7).jpg",
      "/projects/ANIL SHAH/6 (8).jpg",
      "/projects/ANIL SHAH/6 (9).jpg",
    ],
    description:
      "A contemporary residential project featuring modern design elements with elegant finishes.",
    details:
      "This residential project showcases clean lines and carefully curated furnishings.",
    year: "2024",
  },
  {
    id: 2,
    slug: "arjun-pabari-project",
    title: "Arjun Pabari Project",
    category: "Interior Design",
    mainImage: "/projects/ARJUN PABARI/VIEW -01.jpg",
    thumbnail: "/projects/ARJUN PABARI/VIEW -01.jpg",
    images: [
      "/projects/ARJUN PABARI/VIEW -01.jpg",
      "/projects/ARJUN PABARI/VIEW -02.jpg",
      "/projects/ARJUN PABARI/VIEW -03.jpg",
    ],
    description:
      "An elegant interior design project that emphasizes modern aesthetics.",
    details: "A serene design that prioritizes comfort and elegance.",
    year: "2024",
  },
  {
    id: 3,
    slug: "kent-valley-international-school",
    title: "Kent Valley International School",
    category: "Commercial Design",
    mainImage: "/projects/KENT VALLY INTERNATIONAL SCHOOL/BIRD EYE VIEW.jpg",
    thumbnail: "/projects/KENT VALLY INTERNATIONAL SCHOOL/BIRD EYE VIEW.jpg",
    images: [
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/BIRD EYE VIEW.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/03.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/04.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (1).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (2).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (3).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (4).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (5).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (6).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (7).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/1 (8).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/2 (1).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/2 (4).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/2 (5).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/2 (6).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/2 (9).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/22 (2).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/3 (1).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/3 (2).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/3 (3).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/3 (4).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/3 (5).jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/4.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/AUDIO VIDEO ROOM 1.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/AUDIO VIDEO ROOM 2.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/cabin 1-2.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/cabin 2-1.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/CABIN1 1.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/CABIN1 2.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/CABIN2 1.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/CABIN2 2.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/CONFERENCE ROOM 1.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/CONFERENCE ROOM 2.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/work station -1.jpg",
      "/projects/KENT VALLY INTERNATIONAL SCHOOL/work station -2.jpg",
    ],
    description:
      "A comprehensive educational facility design that creates an inspiring learning environment.",
    details:
      "A functional yet beautiful educational space with modern facilities.",
    year: "2023",
  },
  {
    id: 4,
    slug: "kishor-gawas-residence",
    title: "Kishor Gawas Residence",
    category: "Residential Design",
    mainImage: "/projects/KISHOR GAWAS/1.jpg",
    thumbnail: "/projects/KISHOR GAWAS/1.jpg",
    images: [
      "/projects/KISHOR GAWAS/1.jpg",
      "/projects/KISHOR GAWAS/2.jpg",
      "/projects/KISHOR GAWAS/3.jpg",
      "/projects/KISHOR GAWAS/4.jpg",
      "/projects/KISHOR GAWAS/5.jpg",
    ],
    description: "A cozy residential project with comfortable living spaces.",
    details: "An intimate home designed to provide the perfect sanctuary.",
    year: "2023",
  },
  {
    id: 5,
    slug: "mallika-shah-residence",
    title: "Mallika Shah Residence",
    category: "Interior Design",
    mainImage: "/projects/MALLIKA SHAH/1 (3).jpg",
    thumbnail: "/projects/MALLIKA SHAH/1 (3).jpg",
    images: [
      "/projects/MALLIKA SHAH/1 (3).jpg",
      "/projects/MALLIKA SHAH/1 (4).jpg",
      "/projects/MALLIKA SHAH/1 (5).jpg",
      "/projects/MALLIKA SHAH/2 (3).jpg",
      "/projects/MALLIKA SHAH/2 (4).jpg",
      "/projects/MALLIKA SHAH/2 (5).jpg",
      "/projects/MALLIKA SHAH/3 (1).jpg",
      "/projects/MALLIKA SHAH/3 (2).jpg",
      "/projects/MALLIKA SHAH/4 (2).jpg",
    ],
    description:
      "A minimalist home design that emphasizes clean lines and natural materials.",
    details: "A serene home retreat with a calming atmosphere.",
    year: "2024",
  },
  {
    id: 6,
    slug: "mayur-shah-residence",
    title: "Mayur Shah Residence",
    category: "Residential Design",
    mainImage: "/projects/MAYUR SHAH/1 (1).jpg",
    thumbnail: "/projects/MAYUR SHAH/1 (1).jpg",
    images: [
      "/projects/MAYUR SHAH/1 (1).jpg",
      "/projects/MAYUR SHAH/1 (2).jpg",
      "/projects/MAYUR SHAH/1 (3).jpg",
      "/projects/MAYUR SHAH/1 (4).jpg",
      "/projects/MAYUR SHAH/1 (5).jpg",
      "/projects/MAYUR SHAH/1 (6).jpg",
      "/projects/MAYUR SHAH/2 (1).jpg",
      "/projects/MAYUR SHAH/2 (3).jpg",
      "/projects/MAYUR SHAH/2 (4).jpg",
      "/projects/MAYUR SHAH/3 (2).jpg",
      "/projects/MAYUR SHAH/4 (1).jpg",
      "/projects/MAYUR SHAH/4 (2).jpg",
      "/projects/MAYUR SHAH/5 (1).jpg",
      "/projects/MAYUR SHAH/5 (2).jpg",
      "/projects/MAYUR SHAH/6 (1).jpg",
      "/projects/MAYUR SHAH/6 (2).jpg",
      "/projects/MAYUR SHAH/7 (1).jpg",
      "/projects/MAYUR SHAH/7 (2).jpg",
      "/projects/MAYUR SHAH/8 (1).jpeg",
      "/projects/MAYUR SHAH/8 (2).jpeg",
      "/projects/MAYUR SHAH/8 (3).jpeg",
    ],
    description:
      "A modern space that balances functionality with aesthetic appeal.",
    details:
      "Ergonomic solutions and inspiring elements that enhance creativity.",
    year: "2023",
  },
  {
    id: 7,
    slug: "piyush-shah-project",
    title: "Piyush Shah Project",
    category: "Luxury Design",
    mainImage: "/projects/PIYUSH SHAH/IMG_6173-HDR-Pano.jpg",
    thumbnail: "/projects/PIYUSH SHAH/IMG_6173-HDR-Pano.jpg",
    images: [
      "/projects/PIYUSH SHAH/IMG_6173-HDR-Pano.jpg",
      "/projects/PIYUSH SHAH/001.jpg",
      "/projects/PIYUSH SHAH/005.jpg",
      "/projects/PIYUSH SHAH/05.jpg",
      "/projects/PIYUSH SHAH/20220611_193408.jpg",
      "/projects/PIYUSH SHAH/7.jpg",
      "/projects/PIYUSH SHAH/IMG_6306-HDR-2.jpg",
      "/projects/PIYUSH SHAH/IMG_6358-HDR-Pano-3.jpg",
      "/projects/PIYUSH SHAH/IMG_6377-HDR.jpg",
    ],
    description:
      "A luxury design that combines classic sophistication with modern functionality.",
    details: "An elegant space perfect for gatherings and intimate moments.",
    year: "2024",
  },
  {
    id: 8,
    slug: "ramdutt-apartment",
    title: "Ramdutt Apartment",
    category: "Apartment Design",
    mainImage: "/projects/RAMDUTT APARTMENT/1 (1).jpg",
    thumbnail: "/projects/RAMDUTT APARTMENT/1 (1).jpg",
    images: [
      "/projects/RAMDUTT APARTMENT/1 (1).jpg",
      "/projects/RAMDUTT APARTMENT/1 (3).jpg",
      "/projects/RAMDUTT APARTMENT/1 (4).jpg",
      "/projects/RAMDUTT APARTMENT/1 (5).jpg",
      "/projects/RAMDUTT APARTMENT/1 (6).jpg",
      "/projects/RAMDUTT APARTMENT/2 (1).jpg",
    ],
    description:
      "A stylish apartment with custom built-ins and sophisticated lighting.",
    details: "Maximizes storage while maintaining an elegant aesthetic.",
    year: "2023",
  },
  {
    id: 9,
    slug: "shripal-ishan-project",
    title: "Shripal Ishan Project",
    category: "Contemporary Design",
    mainImage: "/projects/SHRIPAL ISHAN/1 (1).jpg",
    thumbnail: "/projects/SHRIPAL ISHAN/1 (1).jpg",
    images: [
      "/projects/SHRIPAL ISHAN/1 (1).jpg",
      "/projects/SHRIPAL ISHAN/1 (12).jpg",
      "/projects/SHRIPAL ISHAN/1 (14).jpg",
      "/projects/SHRIPAL ISHAN/1 (4).jpg",
      "/projects/SHRIPAL ISHAN/1 (5).jpg",
      "/projects/SHRIPAL ISHAN/1 (7).jpg",
      "/projects/SHRIPAL ISHAN/1 (9).jpg",
      "/projects/SHRIPAL ISHAN/2 (1).jpg",
      "/projects/SHRIPAL ISHAN/2 (2).jpg",
      "/projects/SHRIPAL ISHAN/2 (4).jpg",
      "/projects/SHRIPAL ISHAN/2 (5).jpg",
      "/projects/SHRIPAL ISHAN/2 (6).jpg",
      "/projects/SHRIPAL ISHAN/2 (7).jpg",
      "/projects/SHRIPAL ISHAN/3 (4).jpg",
      "/projects/SHRIPAL ISHAN/4 (2).jpg",
      "/projects/SHRIPAL ISHAN/5 (2).jpg",
    ],
    description:
      "A contemporary design blending indoor comfort with natural beauty.",
    details: "Modern materials and thoughtful design elements.",
    year: "2024",
  },
];

export const getProjectBySlug = (slug) => projects.find((p) => p.slug === slug);

export const slugify = (title) =>
  title
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
